Repository dasch-swiss/dsp-tangoh-app, pull requests merged in 2021-04, with the labels that each got.

#7 fix(geoname): add missing logic for Geoname values (DSP-1373)
  app/public/index.html
  app/public/js/00_init_javascript.js
  app/public/js/jquery.geonames.js
  app/public/js/jquery.propedit.js
  app/public/less/jquery-ui.css
Labels: bug

#14 fix(res creation): prevent error when geoname value is empty (DSP-1495)
  app/public/js/jquery.geonames.js
  app/public/js/jquery.resadd.js
Labels: bug

#13 fix(clickable links): wrap URLs with anchor tags (DSP-1490)
  app/public/js/03_showval.js
  app/public/js/jquery.htmleditor.js
Labels: bug

#12 fix(ext search): add case for Boolean value (DSP-1489)
  app/public/js/jquery.extsearch.js
Labels: bug

#16 fix(datepicker): make day selection wider (DSP-1524)
  app/public/js/jquery.dateobj.js
Labels: bug

#15 feat(extended search): add case for URI value (DSP-1521)
  app/public/js/jquery.extsearch.js
Labels: enhancement

#17 feat(clipurl plugin): add plugin (DSP-1494)
  app/public/index.html
  app/public/js/imagebase.js
  app/public/js/jquery.clipurl.js
  app/public/js/jquery.propedit.js
  app/public/test/Gruntfile.js
  app/public/test/package-lock.json
  app/public/test/package.json
  app/public/test/specs/jquery.clipurl.spec.html
Labels: enhancement

#18 feat(ext. search): use labels for ext. search (DSP-1547)
  app/public/js/jquery.extsearch.js
  app/public/lang/de.json
  app/public/lang/en.json
  app/public/lang/fr.json
  app/public/lang/it.json
Labels: enhancement

#21 fix: Fix for image resolution
  app/public/js/imagebase.js
Labels: bug

#20 chore: release 1.1.0
  CHANGELOG.md
  version.txt
Labels: autorelease: pending

#19 fix(grid view): make preview settings consistent with preview image size (DSP-1548)
  app/public/js/02_searchlist.js
Labels: enhancement

#22 feat(value container): add some margin between values (DSP-1552)
  app/public/default.css
Labels: enhancement

#25 feat(ext search): sort props alphabetically (DSP-1572)
  app/public/js/00_init_javascript.js
  app/public/js/jquery.extsearch.js
  app/public/js/jquery.resadd.js
Labels: enhancement

#26 fix(link obj): fix active project when creating a linkage object (DSP-1574)
  app/public/js/imagebase.js
Labels: bug

#27 feat(search): replace default icon (DSP-1573)
  app/public/js/02_searchlist.js
  app/public/js/imagebase.js
  app/public/project-icons/webern/person.png
Labels: enhancement
