Repository dasch-swiss/dsp-tangoh-app, pull requests merged in 2021-03, with the labels that each got.

#6 chore (cypress): run cypress locally
  .gitignore
  e2e/cypress.json
  e2e/integration/BUILD.bazel
  e2e/integration/page.spec.ts
  package.json
Labels: enhancement

#8 fix(window controls): keep ctrl buttons visible (DSP-1384)
  app/public/default.css
  app/public/js/jquery.win.js
  app/public/less/dock.less
Labels: bug

#9 test(resource creation): create simple resource
  e2e/integration/resource-creation.spec.ts
Labels: enhancement

#10 test(resource editing): edit text value
  e2e/cypress.json
  e2e/integration/BUILD.bazel
  e2e/integration/resource-creation.spec.ts
  e2e/integration/resource-editing.spec.ts
Labels: testing
